import * as THREE from 'three'; import type { GeoPlace } from '../types';
const R=6371.0088, rad=(x:number)=>x*Math.PI/180, deg=(x:number)=>x*180/Math.PI;
export const validCoordinates=(lat:number,lon:number)=>Number.isFinite(lat)&&Number.isFinite(lon)&&Math.abs(lat)<=90&&Math.abs(lon)<=180;
export function latLonToVector3(latitude:number,longitude:number,radius=1){const phi=rad(90-latitude),theta=rad(longitude+180);return new THREE.Vector3(-radius*Math.sin(phi)*Math.cos(theta),radius*Math.cos(phi),radius*Math.sin(phi)*Math.sin(theta))}
export function vector3ToLatLon(v:THREE.Vector3){const n=v.clone().normalize();return {latitude:deg(Math.asin(n.y)),longitude:((deg(Math.atan2(n.z,-n.x))-180+540)%360)-180}}
export function haversine(a:GeoPlace,b:GeoPlace){const dLat=rad(b.latitude-a.latitude),dLon=rad(b.longitude-a.longitude),x=Math.sin(dLat/2)**2+Math.cos(rad(a.latitude))*Math.cos(rad(b.latitude))*Math.sin(dLon/2)**2;return 2*R*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
export function bearing(a:GeoPlace,b:GeoPlace){const dl=rad(b.longitude-a.longitude),y=Math.sin(dl)*Math.cos(rad(b.latitude)),x=Math.cos(rad(a.latitude))*Math.sin(rad(b.latitude))-Math.sin(rad(a.latitude))*Math.cos(rad(b.latitude))*Math.cos(dl);return (deg(Math.atan2(y,x))+360)%360}
export function destinationPoint(a:GeoPlace, distanceKm:number, bearingDeg:number){const d=distanceKm/R,t=rad(bearingDeg),p=rad(a.latitude),l=rad(a.longitude);const p2=Math.asin(Math.sin(p)*Math.cos(d)+Math.cos(p)*Math.sin(d)*Math.cos(t));const l2=l+Math.atan2(Math.sin(t)*Math.sin(d)*Math.cos(p),Math.cos(d)-Math.sin(p)*Math.sin(p2));return {latitude:deg(p2),longitude:((deg(l2)+540)%360)-180}}
export function interpolateGreatCircle(a:GeoPlace,b:GeoPlace,steps=96){const av=latLonToVector3(a.latitude,a.longitude),bv=latLonToVector3(b.latitude,b.longitude); const angle=av.angleTo(bv); if(angle<1e-8)return [{...a}]; const pts:GeoPlace[]=[]; for(let i=0;i<=steps;i++){const t=i/steps,s=Math.sin(angle);const v=av.clone().multiplyScalar(Math.sin((1-t)*angle)/s).add(bv.clone().multiplyScalar(Math.sin(t*angle)/s));const c=vector3ToLatLon(v);pts.push({id:`route-${i}`,name:'Route point',type:'coordinate',...c})}return pts}
export function formatCoord(p:GeoPlace|undefined){return p?`${p.latitude.toFixed(4)}°, ${p.longitude.toFixed(4)}°`:'—'}
