from abc import ABC, abstractmethod
from typing import Any


class BaseERPAdapter(ABC):
    @abstractmethod
    async def sync_products(self) -> list[dict[str, Any]]: ...
    @abstractmethod
    async def sync_inventory(self) -> list[dict[str, Any]]: ...
    @abstractmethod
    async def create_order(self, order: dict[str, Any]) -> dict[str, Any]: ...
    @abstractmethod
    async def reserve_order(self, order: dict[str, Any]) -> dict[str, Any]: ...
    @abstractmethod
    async def cancel_order(self, external_id: str) -> dict[str, Any]: ...
